name: SkinGround
author: naeng
main: naeng\SkinGround\SkinGround
version: 2.0.1
api: 5.0.0
depend:
  - XuidCore
  - CooltimeCore
virions:
  - SOF3/await-generator/master
  - RICHMCBE/ExceptionLogger/v1.1.3
